package pkg

import (
	"fmt"
	"os"
)

type LockedPackage struct {
	Name         string
	Version      Version
	Source       string // "git", "path"
	Git          string
	Rev          string
	PathRef      string
	Checksum     string
	Dependencies []string
}

type Lockfile struct {
	Version  int
	Packages []LockedPackage
}

const lockfileVersion = 1

func ReadLockfile(path string) (*Lockfile, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	tv, err := ParseToml(string(src))
	if err != nil {
		return nil, err
	}
	lf := &Lockfile{Version: lockfileVersion}
	if v, ok := tv.Table["version"]; ok && v.Kind == "int" {
		lf.Version = int(v.Int)
	}
	if pkgs, ok := tv.Table["package"]; ok && pkgs.Kind == "array" {
		for _, p := range pkgs.Array {
			if p.Kind != "table" {
				continue
			}
			lp := LockedPackage{}
			if v, ok := p.Table["name"]; ok {
				lp.Name = v.Str
			}
			if v, ok := p.Table["version"]; ok {
				ver, err := ParseVersion(v.Str)
				if err == nil {
					lp.Version = ver
				}
			}
			if v, ok := p.Table["source"]; ok {
				lp.Source = v.Str
			}
			if v, ok := p.Table["git"]; ok {
				lp.Git = v.Str
			}
			if v, ok := p.Table["rev"]; ok {
				lp.Rev = v.Str
			}
			if v, ok := p.Table["path"]; ok {
				lp.PathRef = v.Str
			}
			if v, ok := p.Table["checksum"]; ok {
				lp.Checksum = v.Str
			}
			if v, ok := p.Table["dependencies"]; ok && v.Kind == "array" {
				for _, d := range v.Array {
					if d.Kind == "string" {
						lp.Dependencies = append(lp.Dependencies, d.Str)
					}
				}
			}
			lf.Packages = append(lf.Packages, lp)
		}
	}
	return lf, nil
}

func WriteLockfile(path string, lf *Lockfile) error {
	t := NewTomlTable()
	t.SetField("version", TomlInt(int64(lf.Version)))
	if len(lf.Packages) > 0 {
		arr := NewTomlArray()
		for _, p := range lf.Packages {
			pt := NewTomlTable()
			pt.SetField("name", TomlString(p.Name))
			pt.SetField("version", TomlString(p.Version.String()))
			pt.SetField("source", TomlString(p.Source))
			if p.Git != "" {
				pt.SetField("git", TomlString(p.Git))
			}
			if p.Rev != "" {
				pt.SetField("rev", TomlString(p.Rev))
			}
			if p.PathRef != "" {
				pt.SetField("path", TomlString(p.PathRef))
			}
			pt.SetField("checksum", TomlString(p.Checksum))
			deps := NewTomlArray()
			for _, d := range p.Dependencies {
				deps.Array = append(deps.Array, TomlString(d))
			}
			pt.SetField("dependencies", deps)
			arr.Array = append(arr.Array, pt)
		}
		t.SetField("package", arr)
	}
	header := "# This file is auto-generated by tya install. Do not edit manually.\n"
	return os.WriteFile(path, []byte(header+EmitToml(t)), 0644)
}

func (lf *Lockfile) FindPackage(name string) *LockedPackage {
	for i := range lf.Packages {
		if lf.Packages[i].Name == name {
			return &lf.Packages[i]
		}
	}
	return nil
}

// SatisfiesManifest returns true if the lockfile contains a package entry for
// every dependency in the manifest with a version that satisfies the
// constraint.
func (lf *Lockfile) SatisfiesManifest(m *Manifest) bool {
	for _, name := range m.DepOrder {
		d := m.Deps[name]
		lp := lf.FindPackage(name)
		if lp == nil {
			return false
		}
		switch d.Source {
		case "version":
			if !d.Constraint.Satisfies(lp.Version) {
				return false
			}
		case "git":
			if lp.Source != "git" || lp.Git != d.Git {
				return false
			}
		case "path":
			if lp.Source != "path" || lp.PathRef != d.PathRef {
				return false
			}
		}
		_ = fmt.Sprintf
	}
	return true
}
